### ISSUE TITLE
Can't make it running

### ISSUE THREAD

**Issue by l3lackShark** [calledude/calledudeBot#1]
Hello, thanks for your bot! From what i saw its doing a great job but unfortunately i can't run it for some reason. Whenever i try to run it it will stuck on [Discord] Waiting for OBS or something. Also, I'm pretty sure that this is happening because my Discord can't detect my OBS for some reason. Any solutions? Thanks.

**Comment by calledude** [comment]
The bot at that point is fully functional, except that it won't detect when you start streaming. Chat commands and whatnot still work.
It checks if any OBS process is running on your PC.
As such, I have one question. 
Are you running 32 or 64 bit OBS? (Because it is likely that I messed up the code for detecting the 32-bit version)

**Comment by calledude** [comment]
If you happen to be running the 32bit version of OBS, do you mind checking your process list for me and report back what the name of the .exe file is? Because if it isn't "obs32.exe" I have certainly made an error in assuming it would be named that.

**Comment by l3lackShark** [comment]
Unfortunately I'm using an OBS 64Bit, and the for the process names: 
![image](https://user-images.githubusercontent.com/20248967/52014282-f8729f80-2500-11e9-904e-cfce10ef0363.png)

**Comment by l3lackShark** [comment]
Also, 32bit is the same: 
![image](https://user-images.githubusercontent.com/20248967/52014417-47203980-2501-11e9-980b-d9e9c9f8d13e.png)

**Comment by calledude** [comment]
Just to make sure, do you have [this](https://github.com/Palakis/obs-websocket/releases) plugin installed and enabled for OBS?

I haven't uploaded the latest release fixing this yet (it now prints out a message that prompts you to install it)

I'll get right on uploading the latest version for you :)

**Comment by calledude** [comment]
New version [here](https://github.com/calledude/calledudeBot/releases/tag/v1.1)

Download that and make sure the plugin I mentioned is installed and enabled for port 4444. You can find the settings for the plugin in OBS in the `Tools` dropdown-menu. `Tools->Websocket server settings`

**Comment by calledude** [comment]
Did this work for you? If so, I would appreciate if you could respond so I could close this issue 👍

**Comment by l3lackShark** [comment]
Alright, thanks for the help, It looks like bot successfully connected to the OBS, but I didn't tested it out yet. Thanks for the help, I will reopen this issue if something will go wrong.

**Comment by l3lackShark** [comment]
So apparently the bot still does not work for me, Whenewer I start streaming nothing happens. I'm pretty sure that i setted up everything right... Is there a way to check that is the bot working or not?

**Comment by calledude** [comment]
It'll take a while before it detects that you're streaming. It goes by your state on discord, and that doesn't update immediately. Are you sure your status on discord is streaming? An easy way to check this is if your profile picture has a purple dot next to it.

**Comment by l3lackShark** [comment]
Yep, just checked that it is, alright I will wait some time and will reply back.

**Comment by calledude** [comment]
It shouldn't take more than 30 seconds after your discord status has been updated to streaming. If it still doesn't work then, you have probably messed something up in the configuration of the bot. Are you sure that you have used the correct ID for your discord user? It is important that it is YOUR userID and not the bots ID.

**Comment by l3lackShark** [comment]
I use this one right here: 
![image](https://user-images.githubusercontent.com/20248967/52077348-9f634400-25b2-11e9-8e87-1f3eb433d6f4.png)*
![image](https://user-images.githubusercontent.com/20248967/52077355-a427f800-25b2-11e9-988e-7fca06071084.png) 
Should be correct.
